version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    # entrypoint: [ "yarn", "start:dev" ]

